# Generated by Django 5.0.4 on 2024-04-05 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('auctionid', models.AutoField(db_column='AuctionID', primary_key=True, serialize=False)),
                ('auctiondate', models.DateTimeField(db_column='AuctionDate')),
                ('duration', models.IntegerField(db_column='Duration')),
            ],
            options={
                'db_table': 'Auctions',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('email', models.CharField(db_column='Email', max_length=255, unique=True)),
                ('password', models.CharField(db_column='Password', max_length=255)),
                ('type', models.CharField(db_column='Type', max_length=6)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Auctioneditems',
            fields=[
                ('itemid', models.AutoField(db_column='ItemID', primary_key=True, serialize=False)),
                ('auctionid', models.ForeignKey(db_column='AuctionID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.auctions')),
            ],
            options={
                'db_table': 'AuctionedItems',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('categoryid', models.AutoField(db_column='CategoryID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('parentcategoryid', models.ForeignKey(blank=True, db_column='ParentCategoryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.categories')),
            ],
            options={
                'db_table': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('paymentid', models.AutoField(db_column='PaymentID', primary_key=True, serialize=False)),
                ('paymentamount', models.DecimalField(db_column='PaymentAmount', decimal_places=2, max_digits=10)),
                ('paymentdate', models.DateTimeField(blank=True, db_column='PaymentDate', null=True)),
                ('modeofpayment', models.CharField(blank=True, db_column='ModeOfPayment', max_length=255, null=True)),
                ('paymentstatus', models.CharField(db_column='PaymentStatus', max_length=9)),
                ('auctioneditemid', models.ForeignKey(blank=True, db_column='AuctionedItemID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.auctioneditems')),
                ('buyerid', models.ForeignKey(db_column='BuyerID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
                ('sellerid', models.ForeignKey(db_column='SellerID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='payments_sellerid_set', to='g6app.users')),
            ],
            options={
                'db_table': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('productid', models.AutoField(db_column='ProductID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=255)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('categoryid', models.ForeignKey(blank=True, db_column='CategoryID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.categories')),
                ('ownerid', models.ForeignKey(blank=True, db_column='OwnerID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
        migrations.AddField(
            model_name='auctions',
            name='productid',
            field=models.ForeignKey(blank=True, db_column='ProductID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.products'),
        ),
        migrations.AddField(
            model_name='auctioneditems',
            name='productid',
            field=models.ForeignKey(db_column='ProductID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.products'),
        ),
        migrations.CreateModel(
            name='Shipments',
            fields=[
                ('shipmentid', models.AutoField(db_column='ShipmentID', primary_key=True, serialize=False)),
                ('shippingaddress', models.TextField(db_column='ShippingAddress')),
                ('trackingid', models.CharField(blank=True, db_column='TrackingID', max_length=255, null=True)),
                ('status', models.CharField(db_column='Status', max_length=10)),
                ('shipmentdate', models.DateTimeField(blank=True, db_column='ShipmentDate', null=True)),
                ('estimateddeliverydate', models.DateTimeField(blank=True, db_column='EstimatedDeliveryDate', null=True)),
                ('actualdeliverydate', models.DateTimeField(blank=True, db_column='ActualDeliveryDate', null=True)),
                ('paymentid', models.ForeignKey(db_column='PaymentID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.payments')),
            ],
            options={
                'db_table': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('reportid', models.AutoField(db_column='ReportID', primary_key=True, serialize=False)),
                ('reportdate', models.DateTimeField(db_column='ReportDate')),
                ('reportquery', models.TextField(db_column='ReportQuery')),
                ('content', models.TextField(db_column='Content')),
                ('creatorid', models.ForeignKey(blank=True, db_column='CreatorID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
            ],
            options={
                'db_table': 'Reports',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageid', models.AutoField(db_column='MessageID', primary_key=True, serialize=False)),
                ('content', models.TextField(db_column='Content')),
                ('isread', models.IntegerField(blank=True, db_column='IsRead', null=True)),
                ('timestamp', models.DateTimeField(blank=True, db_column='Timestamp', null=True)),
                ('receiverid', models.ForeignKey(db_column='ReceiverID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='message_receiverid_set', to='g6app.users')),
                ('senderid', models.ForeignKey(db_column='SenderID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
            ],
            options={
                'db_table': 'Message',
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackid', models.AutoField(db_column='FeedbackID', primary_key=True, serialize=False)),
                ('rating', models.IntegerField(db_column='Rating')),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True)),
                ('prodid', models.ForeignKey(db_column='ProdID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.products')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
            ],
            options={
                'db_table': 'Feedback',
            },
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('bidid', models.AutoField(db_column='BidID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('bidtimestamp', models.DateTimeField(blank=True, db_column='BidTimestamp', null=True)),
                ('itemid', models.ForeignKey(blank=True, db_column='ItemID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.auctioneditems')),
                ('bidderid', models.ForeignKey(blank=True, db_column='BidderID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
            ],
            options={
                'db_table': 'Bids',
            },
        ),
        migrations.AddField(
            model_name='auctioneditems',
            name='sellerid',
            field=models.ForeignKey(db_column='SellerID', on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users'),
        ),
        migrations.CreateModel(
            name='Views',
            fields=[
                ('viewid', models.AutoField(db_column='ViewID', primary_key=True, serialize=False)),
                ('viewdate', models.DateTimeField(blank=True, db_column='ViewDate', null=True)),
                ('reportid', models.ForeignKey(blank=True, db_column='ReportID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.reports')),
                ('userid', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='g6app.users')),
            ],
            options={
                'db_table': 'Views',
            },
        ),
    ]
